set-option -g default-terminal "tmux-256color"
# set -ga terminal-overrides ",*256col*:Tc"
# set -sg terminal-overrides "*:RGB"
set-option -ga terminal-features ",alacritty:usstyle"
setenv -g COLORTERM truecolor
# set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
# set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

set -g mouse on

unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

bind r source-file ~/.config/tmux/.tmux.conf

bind-key -r f run-shell "tmux neww tmux-sessionizer"
bind-key -r g run-shell "tmux neww tmux-sessionizer default"

unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# vim-mode copy/paste
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# Ensure window index numbers get reordered on delete.
set-option -g renumber-windows on
# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# set terminal title
set-option -g set-titles on
set-option -g set-titles-string "#W"

# don't rename windows automatically
# set-option -g allow-rename off
# auto rename tmux window to current cwd
set-option -g status-interval 1
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'Nybkox/tmux-ukiyo'

# Theme
set -g @ukiyo-theme "kanagawa/gragon"

set -g @vim_navigator_mapping_left "C-h"
set -g @vim_navigator_mapping_right "C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding
set -g @vim_navigator_prefix_mapping_clear_screen ""

# Auto restore tmux
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '/home/hav/.tmux/plugins/tpm/tpm'
