# Config relating to the Lazygit UI https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  language: 'en'
  timeFormat: 02.01.06
  shortTimeFormat: 15:04
  commitAuthorLongLength: 10
  statusPanelView: allBranchesLog
  sidePanelWidth: 0.20
  # enlargedSideViewLocation: 'top'
git:
  paging:
    colorArg: always
    useConfig: true
  branchLogCmd: "git lf --color=always {{branchName}} --"
  allBranchesLogCmd: "git la --color=always"
