[window]
decorations = "buttonless"
dynamic_padding = false

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000 

[general]
import = [
  "~/.config/alacritty/themes/kanagawa-dragon.toml"
]


live_config_reload = true

